"""Lockstep — verifiable evaluation of private computation.

Top-level convenience re-exports of the Layer 2 public surface.
Substrate adapters and domains live one level deeper and are imported
explicitly by users that need them.
"""

from .evaluation import (
    ZERO_BYTES32,
    Address,
    Bytes32Hex,
    DatasetCommitment,
    DatasetPayload,
    DatasetT,
    DisputePolicy,
    EnclaveAttestation,
    EncryptedSolution,
    Evaluation,
    Evaluator,
    Grader,
    GraderResult,
    HoldoutPolicy,
    Receipt,
    ReceiptKind,
    ScoreDimension,
    SolutionPayload,
    SolutionT,
    SolverInterface,
    ValidationTier,
    canonical_json_bytes,
    clear_registry,
    derive_receipt_id,
    get_evaluator,
    list_evaluators,
    register_evaluator,
    restore_registry,
    snapshot_registry,
)

__all__ = [
    "Address",
    "Bytes32Hex",
    "DatasetCommitment",
    "DatasetPayload",
    "DatasetT",
    "DisputePolicy",
    "EnclaveAttestation",
    "EncryptedSolution",
    "Evaluation",
    "Evaluator",
    "Grader",
    "GraderResult",
    "HoldoutPolicy",
    "Receipt",
    "ReceiptKind",
    "ScoreDimension",
    "SolutionPayload",
    "SolutionT",
    "SolverInterface",
    "ValidationTier",
    "ZERO_BYTES32",
    "canonical_json_bytes",
    "clear_registry",
    "derive_receipt_id",
    "get_evaluator",
    "list_evaluators",
    "register_evaluator",
    "restore_registry",
    "snapshot_registry",
]
